stages:
  data_ingestion:
    cmd: python csr/data_ingestion.py
    deps:
    - csr/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python csr/data_preprocessing.py
    deps:
    - data/raw
    - csr/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python csr/feature_engineering.py
    deps:
    - data/interim
    - csr/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python csr/model_building.py
    deps:
    - data/processed
    - csr/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python csr/model_evaluation.py
    deps:
    - models/model.pkl
    - csr/model_evaluation.py
    metrics:
    - reports/metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
